### ISSUE TITLE
Source an License of the CoreSDK in this repo

### ISSUE THREAD

**Issue by micw** [contiki-ng/coresdk_cc13xx_cc26xx#7]
Hello,

I have tried to figure out the exact version and license of this SDK, so i compared it with official versions from TI.

There is no 4.10.22 available for download. It's only 4.10.0.78 and 4.20.0.35 - nothing in between. None of those matches the version in this repo. Also none of these let me compise contiki-ng (e.g. cc1312 launchpad board) because in source/ti/drivers/rf/RF.h things are completely different between TI's version and the one in this repository.

Also while this repository has a BSD license, the versions vom 4.10 up to some 5.x at TI have a restricted license that does not allow any source redistribution. The license has changed somewhere in the 5.x to a new that (as I read it) allows redistribution.

Can you tell me, what the source of this version is and if I can get a newer 4.x if this somewhere (I'd like to add support for cc1312R7) ?

Kind regards,
Michael.

**Comment by arurke** [comment]
Hi @micw . I believe I have been in your shoes some time ago.

Regarding versioning:
A key point is to understand that CoreSDK is a separate component within the Simplelink SDK, with its own versioning, changelog, etc. For example, the latest Simplelink SDK v7.41.00.17 contains CoreSDK v7.40.04. I don't know of any other way to get CoreSDKs than extracting from a Simplelink SDK. You can find the CoreSDK version within a Simplelink SDK on the website by clicking the "Documentation Overview", and next the "CoreSDK Release Notes". I was able to find CoreSDK v4.10.01 and v4.10.03 (surprisingly I could not find v4.10.02 which is in this repo.) in Simplelink SDKs v3.10.00.53 and v3.10.01.11 respectively.

FYI, a changelog for all CoreSDK versions are available [here](https://software-dl.ti.com/simplelink/esd/simplelink_cc13xx_cc26xx_sdk/7.41.00.17/exports/docs/simplelink_mcu_sdk/changelog_coresdk_cc13xx_cc26xx_7_40_04_00.html).

Regarding licensing:
I am no expert on the subject. But opening the [Software Manifest for the latest Simplelink SDK](https://software-dl.ti.com/simplelink/esd/simplelink_cc13xx_cc26xx_sdk/7.41.00.17/exports/manifest_simplelink_cc13xx_cc26xx_sdk_7_41_00_17.html) it lists the CoreSDK license as "BSD-3-Clause".

Regarding cc1312R7:
I had some confusion about the support for this chip as well. Although I believe I could make it work for earlier versions, [the official word I got from TI](https://e2e.ti.com/support/wireless-connectivity/sub-1-ghz-group/sub-1-ghz/f/sub-1-ghz-forum/1178585/cc1312r7-coresdk-version-to-use-for-cc1312r7) was to use CoreSDK v6.10.00 or later.

**Comment by micw** [comment]
That's very interesting. Thank you very much for the clarification.
I am able to build Contiki-NG for cc1312R7 using Simplelink SDK 4.40 which contains the CoreSDK 5.40.02.00 and also contains new stuff for the cc1312R7. The first Simplelink SDK that has cc1312r7 in it's release notes is 5.10.0, see https://software-dl.ti.com/simplelink/esd/simplelink_cc13x2_26x2_sdk/5.10.00.48/exports/release_notes_simplelink_cc13x2_26x2_sdk_5_10_00_48.html#device-support - that's just one version later.

I have created an internal document how we strip down the Simplelink SDK to something that is needed to compile for CC1312R7. Interestingly that is a 100% subset of the files described as "Core SDK" in the SDK Software manifest. 

I have reviewed the license manifest and documented how to extract the Core SDK. Here is a PR for the latest version I'm able to build against without significant changes: https://github.com/contiki-ng/coresdk_cc13xx_cc26xx/pull/8

**Comment by Jpereirafer** [comment]
Hi @micw , I'm trying to get the CC1312R7 chip working using the SDK update you shared in #8 . So far, I’m able to compile the project, but when I load the code, the chip keeps restarting. It's code that I know works, as I have it running on the CC1312R1. To make it work with the CC1312R7, did you modify anything besides the Makefiles and startup files?

**Comment by micw** [comment]
Can you see in which phase the chip is restarting?

What I did is, I started from scratch and copied file by file from simplelink-cc13xx-cc26xx. Here's an excerpt from my worklog:

* rtimer-arch.h unchanged
* rtimer-arch.c unchanged
* cc13xx-cc26xx-def.h unchanged
* cc13xx-cc26xx-conf.h CSMA_CONF_ACK_WAIT_TIME changed but that's probably some internal stuff of ours
* rf.h unchanged
* cc13xx-50kbps-tsch.h unchangec
* cc13xx-50kbps-tsch.c skipped (we don't use that)
* gpio-hal-arch.h - created an empty file to make it compile. must be re-implemented using the new SDK
* copied cc13x2x7-cc26x2x7.lds from the sdk
* Added libraries from Simplelink SDK to linker path
* created platform.c
    * just added empty functions to make the linker happy
        * platform_init_stage_one()
        * platform_init_stage_two()
        * platform_init_stage_three()
        * platform_idle()
* clock-arch.h unchanged
* clock-arch.c unchanged
* watchdog-arch.h unchanged
* watchdog-arch.c unchanged
* created empty Board.h
    * Added Watchdog settings REMARK see below, replaced later, so can be skipped)
* created empty dbg-arch.c
    * just added empty functions to make the linker happy
        * dbg_send_bytes()
        * dbg_putchar()
* created empty prop-mode.c
    * just added empty functions to make the linker happy (see struct radio_driver prop_mode_driver for a list)

This gave me a compilable result.

* created boards/mycustomboard
* created board.syscfg and Makefile.mycustomboard
  * Adapted the syscfg stuff from the ti examples (need to register + download the SDK because the examples are not on github)
* Changed platform.c
    * platform_init_stage_one: Call Board_init() from ti_drivers_config.h to initialize the Hardware
* Added Watchdog to board.syscfg and removed watchdog settings from Board.h
* In platform.c
    * platform_init_stage_one: added NoRTOS_start()
    * platform_idle: copied from contiki-ng/arch/platform/simplelink/cc13xx-cc26xx/platform.c

Uart:

* Added UART2_0 via syscfg
* copied contiki-ng/arch/cpu/simplelink-cc13xx-cc26xx/dev/uart0-arch.h
    * TI "UART" lib is replaced by "UART2" -> migrated
* copied contiki-ng/arch/cpu/simplelink-cc13xx-cc26xx/dev/uart0-arch.c
    * TI "UART" lib is replaced by "UART2" -> migrated
* copied contiki-ng/arch/cpu/simplelink-cc13xx-cc26xx/dev/dbg-arch.c
    * Replaces dbg-arch.c from above
* In platform.c
    * platform_init_stage_two: add uart0_init();

With this you should get a working minimal version. Important here is that one can use syscfg-gui to configure one's board rather than editing the generated files manually.

I later added:
* Radio stuff (normally unchanged from simplelink-cc13xx-cc26xx but in our particular case we use a very customized radio settings, nothing I can share here)
* Implemented dev/gpio-hal-arch.c
    * This part of the library has completely changed but re-implementing was very straightforward. let me know when you need help here
* spi-arch.c: removed the include of PINCC26XX.h. It's not used at all, so could also be removed from simplelink-cc13xx-cc26xx

Let me know if you have a public fork where I can see what you're doing. Then I can also test it on my side and give you some hints.

**Comment by Jpereirafer** [comment]
@micw Thank you very much for your help . I’d say the reset is likely due to a misconfiguration in the memory map, since I’ve encountered issues during compilation involving the .lds files, startup_gcc.c, and nortos_cc13x2x7.am4fg. Not even a single line of my main code gets executed. The failure probably is produced in the gpios initialisation, dio6 and dio7 power up its leds and then the system reboots.

The procedure I followed is the following: I replaced the kernel and source folders with the ones from SDK 5.40. In theory, this version still uses the PINCC26XX.h library, so I haven’t modified anything there. I also updated the platform/simplelink folder to create a dedicated folder for the CC1312R7. Lastly, I modified all the Makefiles to point to the files corresponding to the CC1312R7.
Are you working with the 5.40 SDK or newer?

**Comment by micw** [comment]
Ah sorry, forgot to mention it here, see last comment in https://github.com/contiki-ng/contiki-ng/issues/1956
TI open-sourced the SDK, I'm using version 7.10. I would not stick with that old stuff here anymore.

**Comment by Jpereirafer** [comment]
Hello again , I tried your solution with SDK version 7.10 and everything seems correct. However, I’m having problems during the linking phase. I copied the .lds file from the TI repository, the startup.gcc file and the nortos_cc13x2x7.a file but I get an error similar to this: 

/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: build/simplelink/launchpad/cc1312r7/obj/startup_cc13xx_cc26xx_gcc.o: in function `zero_loop':
startup_cc13xx_cc26xx_gcc.c:(.text.ResetISR+0x44): undefined reference to `__data_start__'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: startup_cc13xx_cc26xx_gcc.c:(.text.ResetISR+0x48): undefined reference to `__data_load__'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: startup_cc13xx_cc26xx_gcc.c:(.text.ResetISR+0x4c): undefined reference to `__data_end__'  
... and so on

It says that some variables are missing but this variables are those that were used in previous SDK versions (such as  __data_load__, __bss_data__ ... ) and I don’t have any file with this variables.. Any clue?
